detector_dl_node:
  ros__parameters:
    5P_NUM_CLASSES: 3
    4P_NUM_CLASSES: 36
    5P_TARGET_COLOUR: "R" #RED
    4P_TARGET_COLOUR: "GREEN"
    NMS_THRESH: 0.1
    BBOX_CONF_THRESH: 0.9
    INPUT_W: 640
    INPUT_H: 640
    5P_CKPT_NUM: 5
    4P_CKPT_NUM: 4
    5P_engine_file_path: "/home/nvidia/mosas_autoaim_dl_dart/src/detector_dl/model/5points_buff.trt"
    4P_engine_file_path: "/home/nvidia/mosas_autoaim_dl_dart/src/detector_dl/model/GreenDot.trt"
