robot_tracker_node: 
  ros__parameters: 
    target_frame: "odom"
    max_armor_distance: 10.0
    max_z: 1.2
    
    tracker: 
      max_match_distance: 0.5
      max_match_yaw_diff_: 1.0
      tracking_thres: 5
      lost_time_thres: 0.15

    ekf:
      s2qxyz: 0.05
      s2qyaw: 5.0
      s2qr_: 80.0
      r_xyz_factor: 0.0004
      r_yaw: 0.005
